### ISSUE TITLE
More FAQs

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-faq#64]
1. Where can I find the list of RingCentral SDKs?
1. How to deal with Unauthorized for this grant type issue?
1. Where can I find a demo for the authorization code flow, a.k.a. 3-legged authorization flow?
1. How can I graduate my app (turn my sandbox app into production)?
1. I want to receive notifications for incoming calls and SMS messages, what should I do?
1. I forget my sandbox account password, how to reset it?
1. How can I start RingCentral app to dial a number via command line?
1. I can only get call logs for the last 24 hours via API, what should I do?
1. How can I get call logs for all users and extensions?
1. What’s the proper way to iterate all pages of call logs?
1. Which official C# SDK should be used?
1. Which API is required permission WebRTC VOIP Calling?
1. What is the API endpoint for InternalMessages permission?
1. Where could I lookup my Account ID and Extension ID?
1. What is RingCentral Data Retention Policy?
    1. How long are the call recordings retained?
1. Why isn't password authorization flow available for public applications?
1. What are the differences between extension number and extension ID?
1. What are the requirements for RingCentral WebHook uri?
1. How to send Fax via curl?
1. How to do password authorization to obtain access token via curl?
1. Is there any way to get phone number from contact name?
1. What are the differences between my developer account and my sandbox account?
1. Where can I find the API call rate limit page?
1. What does "Mailbox has no permission to this action" mean when trying to do ring out via API?
1. Is it possible to make a phone call inside a web browser?
1. How to use RingCentral together with React?
1. How should I handle "Service is overloaded, please retry later"?
1. Where can I find account credentials to do testing in sandbox?
1. The C# SDK provides async style APIs, what are the proper ways to invoke them?
1. How can i add new permissions to an app which is already in Production?
1. I want to disable expires for access_token and refresh_token, is that doable?
1. Can I use my production credentials for sandbox or vice versa?
1. Why can't my Canadian customers login my app?
1. What do RingCentral account and extension mean, respectively?
1. How can I set the presence of the current logged in user via API?
1. How can I resend a fax using RingCentral C# SDK?
1. Where should I turn to if I have a non-programming question about RingCentral?
1. How long should I wait after call ended in order to download the call recording?
1. Where is the list of supported subscription event filters?
1. How do I know that two call log records are two legs of the same call instead of two separate calls?
1. Can I try the API quickly without writting any code?
1. Where is the RingCentral API reference page?
1. How can I disable cover page when sending a fax?
1. How can I monitor a call queue?
1. How to test the email to fax feature in sandbox?
1. How can I integrate inbound call screen pop feature into my CRM?
1. What is an extension number and what is an extension ID?
1. How can I check SMS history?
1. Is there a maximum number of access tokens that a single user could create?
1. Can I fax an HTML page with inline images?
1. How to programmatically dial a number?
1. How to use Alexa as my Personal RingCentral Messaging Assistant?
1. How to create Self-Service Public Glip Teams?
1. How to produce call recordings in sandbox for testing purpose?
1. How to enroll in RingCentral beta program?
1. How to catch the print exceptions with RingCentral C# SDK?
1. What is the maximum number of recipients allowed for MMS?
1. What are verification token and validation token for RingCentral WebHook?
1. How to customize fax cover page?

**Comment by grokify** [comment]
Looks good @tylerlong 

Can you categorize these into the following (or new) categories. Then we can identify the best people to answer each.

* [RingCentral Basics](docs/basics.md)
* [API Usage Plans](docs/api_usage_plan.md)
* [Authentication & Authorization](docs/oauth.md)
* [Account Info](docs/account.md)
* [Voice via RingOut](docs/voice_ringout.md)
* [Voice via WebRTC](docs/voice_webrtc.md)
* [Voice Call Recordings](docs/voice_recording.md)
* [SMS](docs/sms.md)
* [Fax](docs/fax.md)
* [Call Log](docs/call_log.md)
* [Phone Numbers](docs/phone_numbers.md)
* [Notifications & Subscriptions](docs/notifications_subscriptions.md)
* [Webhooks](docs/webhooks.md)
* [Custom Error Codes](docs/errors.md)
* [Upgrading from Legacy APIs](docs/legacy_ringout_faxout_apis.md)

**Comment by tylerlong** [comment]
## [RingCentral Basics](/ringcentral/ringcentral-faq/blob/master/docs/basics.md)

## [API Usage Plans](/ringcentral/ringcentral-faq/blob/master/docs/api_usage_plan.md)

## [Authentication & Authorization](/ringcentral/ringcentral-faq/blob/master/docs/oauth.md)

## [Account Info](/ringcentral/ringcentral-faq/blob/master/docs/account.md)

## [Voice via RingOut](/ringcentral/ringcentral-faq/blob/master/docs/voice_ringout.md)

## [Voice via WebRTC](/ringcentral/ringcentral-faq/blob/master/docs/voice_webrtc.md)

## [Voice Call Recordings](/ringcentral/ringcentral-faq/blob/master/docs/voice_recording.md)

## [SMS](/ringcentral/ringcentral-faq/blob/master/docs/sms.md)

## [Fax](/ringcentral/ringcentral-faq/blob/master/docs/fax.md)

## [Call Log](/ringcentral/ringcentral-faq/blob/master/docs/call_log.md)

## [Phone Numbers](/ringcentral/ringcentral-faq/blob/master/docs/phone_numbers.md)

## [Notifications & Subscriptions](/ringcentral/ringcentral-faq/blob/master/docs/notifications_subscriptions.md)

## [Webhooks](/ringcentral/ringcentral-faq/blob/master/docs/webhooks.md)

## [Custom Error Codes](/ringcentral/ringcentral-faq/blob/master/docs/errors.md)

## [Upgrading from Legacy APIs](/ringcentral/ringcentral-faq/blob/master/docs/legacy_ringout_faxout_apis.md)

**Comment by dibyenduroy** [comment]
@tylerlong @grokify can you please clarify the question "Which API is required permission WebRTC VOIP Calling?"

**Comment by tylerlong** [comment]
@dibyenduroy  https://devcommunity.ringcentral.com/ringcentraldev/topics/which-api-is-required-permisson-voip-calling

**Comment by grokify** [comment]
Note, when quoting URLs, please use backticks, for example:

**Don't Use**

"https://platform.ringcentral.com/restapi/oauth/token"

**Use**

`https://platform.ringcentral.com/restapi/oauth/token`

**Comment by grokify** [comment]
Also, when building answers for these, be sure to check the Dev Community (https://devcommunity.ringcentral.com) to see if the question has been answered already.

**Comment by tylerlong** [comment]
I created the list of questions. Almost All of the questions could be found from the Dev Community.

**Comment by dibyenduroy** [comment]
@tylerlong @grokify  here are my set of FAQ Q&A - https://docs.google.com/document/d/1hWy5fZ6aMkT0QZvguN3Bv5XHSzVgHrYFYnCSlLLRa-g/edit#
will someone verify and upload to FAQ section or shall we go ahead and upload

**Comment by tylerlong** [comment]
@dibyenduroy You can create a PR here so we can review.

**Comment by dibyenduroy** [comment]
@tylerlong created a PR, please review and merge accordingly, let me know if any changes needed.

**Comment by tylerlong** [comment]
All done.
